services:
  postgres:
    image: postgres:16.9-alpine
    container_name: exam-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: examdb
      POSTGRES_USER: examuser
      POSTGRES_PASSWORD: exampass
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - exam-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U examuser -d examdb"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build:
      context: ./exam-api
      dockerfile: Dockerfile
    container_name: exam-api
    ports:
      - "9000:9000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - exam-network
    restart: unless-stopped

volumes:
  postgres-data:
    name: exam-postgres-data

networks:
  exam-network:
    name: exam-network
